name: NaaT CDN

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: 3.5
    - name: Install Dependencies
      run: |
        pip install b2
        apt update && apt install -y curl
    - name: Upload Files
      env:
        CF_EMAIL: ${{ secrets.CF_EMAIL }}
        CF_SECRET: ${{ secrets.CF_SECRET }}
        CF_ZONE: ${{ secrets.CF_ZONE }}
        B2_ID: ${{ secrets.B2_ID }}
        B2_SECRET: ${{ secrets.B2_SECRET }}
      run: |
        b2 authorize_account $B2_ID $B2_SECRET
        b2 upload_file notanotheranimetheme css/scsl.css scsl.css
        b2 upload_file notanotheranimetheme css/dcsl.css dcsl.css
        b2 upload_file notanotheranimetheme css/tcsl.css tcsl.css
        b2 upload_file notanotheranimetheme css/qcsl.css qcsl.css
        curl -X POST "https://api.cloudflare.com/client/v4/zones/$CF_ZONE/purge_cache" -H "X-Auth-Email: $CF_EMAIL" -H "X-Auth-Key: $CF_SECRET" -H "Content-Type: application/json" --data '{"files":["https://cdn.discordthemes.net/file/notanotheranimetheme/scsl.css", "https://cdn.discordthemes.net/file/notanotheranimetheme/dcsl.css", "https://cdn.discordthemes.net/file/notanotheranimetheme/tcsl.css", "https://cdn.discordthemes.net/file/notanotheranimetheme/qcsl.css"]}'
